sudo: true

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest -VV

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false
