sudo: required

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get -qq update
  - sudo apt-get install -y openmpi-bin libopenmpi-dev libhdf5-openmpi-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest -VV

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false
